apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: appcket-gateway
  namespace: appcket
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
    hosts:
    - "appcket.localhost"
    - "accounts.appcket.localhost"
    - "api.appcket.localhost"
    - "app.appcket.localhost"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "appcket.localhost"
    - "accounts.appcket.localhost"
    - "api.appcket.localhost"
    - "app.appcket.localhost"