services:
  registry:
    image: registry:3
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
    volumes:
      - ./registry:/var/lib/registry
  database:
    image: postgres:18
    environment:
      POSTGRES_DB: appcket
      POSTGRES_ROOT_PASSWORD: Ch@ng3To@StrongP@ssw0rd
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: Ch@ng3To@StrongP@ssw0rd
    command: ["postgres", "-c", "wal_level=logical"]
    ports:
      - 5432:5432
    volumes:
      - appcket-database:/var/lib/postgresql:Z
      - ./:/tmp
  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - appcket-redis-data:/data
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest-alpine
    restart: unless-stopped
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native client interface
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_DB: appcket
      CLICKHOUSE_USER: dbuser
      CLICKHOUSE_PASSWORD: Ch@ng3To@StrongP@ssw0rd
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    extra_hosts:
      - "redpanda-0.127.0.0.1.nip.io:host-gateway"
      - "host.docker.internal:host-gateway"
volumes:
  appcket-database:
    external: true
  appcket-redis-data: