/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as TeamsCreateRouteImport } from './routes/teams/create'
import { Route as TasksCreateRouteImport } from './routes/tasks/create'
import { Route as ProjectsCreateRouteImport } from './routes/projects/create'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiCallbackRouteImport } from './routes/api/callback'
import { Route as TeamsTeamIdIndexRouteImport } from './routes/teams/$teamId.index'
import { Route as TasksTaskIdIndexRouteImport } from './routes/tasks/$taskId.index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId.index'
import { Route as TeamsTeamIdEditRouteImport } from './routes/teams/$teamId.edit'
import { Route as TasksTaskIdEditRouteImport } from './routes/tasks/$taskId.edit'
import { Route as ProjectsProjectIdTasksRouteImport } from './routes/projects/$projectId.tasks'
import { Route as ProjectsProjectIdEditRouteImport } from './routes/projects/$projectId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsCreateRoute = TeamsCreateRouteImport.update({
  id: '/teams/create',
  path: '/teams/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksCreateRoute = TasksCreateRouteImport.update({
  id: '/tasks/create',
  path: '/tasks/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCreateRoute = ProjectsCreateRouteImport.update({
  id: '/projects/create',
  path: '/projects/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallbackRoute = ApiCallbackRouteImport.update({
  id: '/api/callback',
  path: '/api/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdIndexRoute = TeamsTeamIdIndexRouteImport.update({
  id: '/teams/$teamId/',
  path: '/teams/$teamId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdIndexRoute = TasksTaskIdIndexRouteImport.update({
  id: '/tasks/$taskId/',
  path: '/tasks/$taskId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdEditRoute = TeamsTeamIdEditRouteImport.update({
  id: '/teams/$teamId/edit',
  path: '/teams/$teamId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdEditRoute = TasksTaskIdEditRouteImport.update({
  id: '/tasks/$taskId/edit',
  path: '/tasks/$taskId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdTasksRoute = ProjectsProjectIdTasksRouteImport.update({
  id: '/projects/$projectId/tasks',
  path: '/projects/$projectId/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdEditRoute = ProjectsProjectIdEditRouteImport.update({
  id: '/projects/$projectId/edit',
  path: '/projects/$projectId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/api/callback': typeof ApiCallbackRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/tasks/create': typeof TasksCreateRoute
  '/teams/create': typeof TeamsCreateRoute
  '/projects/': typeof ProjectsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/$projectId/tasks': typeof ProjectsProjectIdTasksRoute
  '/tasks/$taskId/edit': typeof TasksTaskIdEditRoute
  '/teams/$teamId/edit': typeof TeamsTeamIdEditRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/tasks/$taskId/': typeof TasksTaskIdIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/api/callback': typeof ApiCallbackRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/tasks/create': typeof TasksCreateRoute
  '/teams/create': typeof TeamsCreateRoute
  '/projects': typeof ProjectsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/$projectId/tasks': typeof ProjectsProjectIdTasksRoute
  '/tasks/$taskId/edit': typeof TasksTaskIdEditRoute
  '/teams/$teamId/edit': typeof TeamsTeamIdEditRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/tasks/$taskId': typeof TasksTaskIdIndexRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/api/callback': typeof ApiCallbackRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/tasks/create': typeof TasksCreateRoute
  '/teams/create': typeof TeamsCreateRoute
  '/projects/': typeof ProjectsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/$projectId/tasks': typeof ProjectsProjectIdTasksRoute
  '/tasks/$taskId/edit': typeof TasksTaskIdEditRoute
  '/teams/$teamId/edit': typeof TeamsTeamIdEditRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/tasks/$taskId/': typeof TasksTaskIdIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/api/callback'
    | '/api/login'
    | '/api/logout'
    | '/projects/create'
    | '/tasks/create'
    | '/teams/create'
    | '/projects/'
    | '/teams/'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/tasks'
    | '/tasks/$taskId/edit'
    | '/teams/$teamId/edit'
    | '/projects/$projectId/'
    | '/tasks/$taskId/'
    | '/teams/$teamId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/api/callback'
    | '/api/login'
    | '/api/logout'
    | '/projects/create'
    | '/tasks/create'
    | '/teams/create'
    | '/projects'
    | '/teams'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/tasks'
    | '/tasks/$taskId/edit'
    | '/teams/$teamId/edit'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/api/callback'
    | '/api/login'
    | '/api/logout'
    | '/projects/create'
    | '/tasks/create'
    | '/teams/create'
    | '/projects/'
    | '/teams/'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/tasks'
    | '/tasks/$taskId/edit'
    | '/teams/$teamId/edit'
    | '/projects/$projectId/'
    | '/tasks/$taskId/'
    | '/teams/$teamId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ApiCallbackRoute: typeof ApiCallbackRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ProjectsCreateRoute: typeof ProjectsCreateRoute
  TasksCreateRoute: typeof TasksCreateRoute
  TeamsCreateRoute: typeof TeamsCreateRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  ProjectsProjectIdEditRoute: typeof ProjectsProjectIdEditRoute
  ProjectsProjectIdTasksRoute: typeof ProjectsProjectIdTasksRoute
  TasksTaskIdEditRoute: typeof TasksTaskIdEditRoute
  TeamsTeamIdEditRoute: typeof TeamsTeamIdEditRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  TasksTaskIdIndexRoute: typeof TasksTaskIdIndexRoute
  TeamsTeamIdIndexRoute: typeof TeamsTeamIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/create': {
      id: '/teams/create'
      path: '/teams/create'
      fullPath: '/teams/create'
      preLoaderRoute: typeof TeamsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/create': {
      id: '/tasks/create'
      path: '/tasks/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof TasksCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/create': {
      id: '/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof ProjectsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/callback': {
      id: '/api/callback'
      path: '/api/callback'
      fullPath: '/api/callback'
      preLoaderRoute: typeof ApiCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/': {
      id: '/teams/$teamId/'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof TeamsTeamIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId/': {
      id: '/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof TasksTaskIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/edit': {
      id: '/teams/$teamId/edit'
      path: '/teams/$teamId/edit'
      fullPath: '/teams/$teamId/edit'
      preLoaderRoute: typeof TeamsTeamIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId/edit': {
      id: '/tasks/$taskId/edit'
      path: '/tasks/$taskId/edit'
      fullPath: '/tasks/$taskId/edit'
      preLoaderRoute: typeof TasksTaskIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/tasks': {
      id: '/projects/$projectId/tasks'
      path: '/projects/$projectId/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof ProjectsProjectIdTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/edit': {
      id: '/projects/$projectId/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof ProjectsProjectIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ApiCallbackRoute: ApiCallbackRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ProjectsCreateRoute: ProjectsCreateRoute,
  TasksCreateRoute: TasksCreateRoute,
  TeamsCreateRoute: TeamsCreateRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  ProjectsProjectIdEditRoute: ProjectsProjectIdEditRoute,
  ProjectsProjectIdTasksRoute: ProjectsProjectIdTasksRoute,
  TasksTaskIdEditRoute: TasksTaskIdEditRoute,
  TeamsTeamIdEditRoute: TeamsTeamIdEditRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  TasksTaskIdIndexRoute: TasksTaskIdIndexRoute,
  TeamsTeamIdIndexRoute: TeamsTeamIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
